columns:
- id
- budget
- genres
- homepage
- keywords
- original_language
- original_title
- overview
- popularity
- production_companies
- production_countries
- release_date
- revenue
- runtime
- spoken_languages
- status
- tagline
- title
- vote_average
- vote_count
- movie_id
- cast
- crew

selected_columns:
- id
- title
- overview
- genres
- keywords
- cast
- crew
